<?php

namespace App\Http\Requests\OpenAPI\PG\TransferVA;

use App\Helpers\DataTypeCaster;
use App\Http\Resources\OpenAPI\PG\TransferVA\TVAPaymentResource;
use App\Models\Oauth\OauthClientMetadata;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;

class TVAPaymentRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            /**
             * Derivative of X-PARTNER-ID, similar to company code, 8 digit left padding space “ “
             *
             * @example    51112
             * */
            'partnerServiceId' => 'required|string|max:8',

            /**
             * Unique number (up to 20 digits)
             *
             * @example 512234567890
             * */
            'customerNo' => 'required|string|regex:/^\d{1,20}$/|max:20',

            /**
             * partnerServiceId (8 digit left padding space “ “) + customerNo (up to 20 digit)
             *
             * @example    51112512234567890
             * */
            'virtualAccountNo' => 'required|string|max:28',

            /**
             * Customer's Name
             *
             * @example Monsieur Haidar
             * */
            'virtualAccountName' => 'nullable|string|max:255',

            /**
             * Customer's Email
             *
             * @example customer@email.com
             * */
            'virtualAccountEmail' => 'nullable|string|max:255',

            /**
             * Customer's Phone Number
             *
             * @example 62xxx
             * */
            'virtualAccountPhone' => 'nullable|string|max:30',

            /** Unique identifier generated by Partner. Mandatory if payment comes from the Create VA Request */
            'trxId' => 'nullable|string|max:64',

            /** Unique identifier generated by Partner. If payment comes from the Inquiry process, this value must be the same with inquiryRequestId. */
            'paymentRequestId' => 'required|string|max:128',

            /** Channel code based on ISO 18245 */
            'channelCode' => 'nullable|numeric|digits:4',

            /** Optional. Source account in hash */
            'hashedSourceAccountNo' => 'nullable|string|regex:/^[a-zA-Z0-9]+$/|max:32',

            /** Optional. Source account bank code */
            'sourceBankCode' => 'nullable|string|regex:/^\d{3}$/|size:3',

            'paidAmount' => 'required',
            /**
             * Transaction Amount. Nominal inputted by Customer with 2 decimal
             *
             * @example 10000.00
             * */
            'paidAmount.value' => 'required_with:paidAmount|string|regex:/^\d+\.00$/',
            /** Currency */
            'paidAmount.currency' => 'required_with:paidAmount|string|in:IDR,USD|size:3',

            'cumulativePaymentAmount' => 'nullable',
            /**
             * Transaction Amount. Nominal inputted by Customer with 2 decimal
             *
             * @example 10000.00
             * */
            'cumulativePaymentAmount.value' => 'required_with:cumulativePaymentAmount|string|regex:/^\d+(\.\d{1,2})?$/',
            /** Currency */
            'cumulativePaymentAmount.currency' => 'required_with:cumulativePaymentAmount|string|in:IDR,USD|size:3',

            /** Hexadecimal format of binary of paid bills */
            'paidBills' => 'nullable|string|max:6',

            'totalAmount' => 'nullable',
            /**
             * Transaction Amount. Nominal inputted by Customer with 2 decimal
             *
             * @example 10000.00
             * */
            'totalAmount.value' => 'required_with:totalAmount|string|regex:/^\d+\.00$/',
            /** Currency */
            'totalAmount.currency' => 'required_with:totalAmount|string|in:IDR,USD|size:3',

            /**
             * System datetime with timezone, which follows the ISO-8601 standard
             *
             * @example 2025-03-29T21:06:32+07:00
             * */
            'trxDateTime' => 'nullable|date_format:Y-m-d\TH:i:sP|size:25',

            /** Payment auth code generated by partner */
            'referenceNo' => 'nullable|string|max:64',

            /** Sequence journal number */
            'journalNum' => 'nullable|string|max:6',

            /** Type of payment */
            'paymentType' => 'nullable|string|max:1',

            /** Status is this a retry notification. (Default value: N) */
            'flagAdvise' => 'nullable|string|max:1',

            /** Sub Company code generated by Partner */
            'subCompany' => 'nullable|string|max:5',

            /** Array with maximum 24 Objects */
            'billDetails' => 'nullable|array|max:24',
            /** From Inquiry Response */
            'billDetails.*.billCode' => 'nullable|string|max:2',
            /** From Inquiry Response */
            'billDetails.*.billNo' => 'nullable|string|max:18',
            /** From Inquiry Response */
            'billDetails.*.billName' => 'nullable|string|max:20',
            /** From Inquiry Response */
            'billDetails.*.billShortName' => 'nullable|string|max:10',
            /** From Inquiry Response */
            'billDetails.*.billDescription' => 'nullable|array',
            /** From Inquiry Response */
            'billDetails.*.billDescription.english' => 'nullable|string|max:18',
            /** From Inquiry Response */
            'billDetails.*.billDescription.indonesia' => 'nullable|string|max:18',
            /** From Inquiry Response */
            'billDetails.*.billSubCompany' => 'nullable|string|max:5',
            'billDetails.*.billAmount' => 'nullable|array',
            /**
             * Transaction Amount. Nominal inputted by Customer with 2 decimal
             *
             * @example 10000.00
             * */
            'billDetails.*.billAmount.value' => 'required_with:billDetails.*.billAmount|string|regex:/^\d{1,16}(\.\d{2})$/',
            /** Currency */
            'billDetails.*.billAmount.currency' => 'required_with:billDetails.*.billAmount|string|in:IDR,USD|size:3',
            /** From Inquiry Response */
            'billDetails.*.additionalInfo' => 'nullable|array',
            /** From Inquiry Response */
            'billDetails.*.billReferenceNo' => 'nullable|numeric',

            /** From Inquiry Response */
            'freeTexts' => 'nullable|array',
            /** From Inquiry Response */
            'freeTexts.*.english' => 'nullable|string|max:32',
            /** From Inquiry Response */
            'freeTexts.*.indonesia' => 'nullable|string|max:32',

            /** Additional Information for custom use */
            'additionalInfo' => 'nullable|array',
            'additionalInfo.*.label.english' => 'nullable|string|max:50',
            'additionalInfo.*.label.indonesia' => 'nullable|string|max:50',
            'additionalInfo.*.value.english' => 'nullable|string|max:200',
            'additionalInfo.*.value.indonesia' => 'nullable|string|max:200',
        ];
    }

    /**
     * Custom error messages for validation rules.
     *
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            // partnerServiceId Validation Messages
            'partnerServiceId.required' => 'Invalid Mandatory Field {partnerServiceId}',
            'partnerServiceId.string' => 'Invalid Field Format partnerServiceId',
            'partnerServiceId.regex' => 'Invalid Field Format partnerServiceId',
            'partnerServiceId.max' => 'Invalid Field Format partnerServiceId',

            // customerNo Validation Messages
            'customerNo.required' => 'Invalid Mandatory Field {customerNo}',
            'customerNo.string' => 'Invalid Field Format customerNo',
            'customerNo.regex' => 'Invalid Field Format customerNo',
            'customerNo.max' => 'Invalid Field Format customerNo',

            // virtualAccountNo Validation Messages
            'virtualAccountNo.required' => 'Invalid Mandatory Field {virtualAccountNo}',
            'virtualAccountNo.string' => 'Invalid Field Format virtualAccountNo',
            'virtualAccountNo.max' => 'Invalid Field Format virtualAccountNo',

            // virtualAccountName Validation Messages
            'virtualAccountName.string' => 'Invalid Field Format virtualAccountName',
            'virtualAccountName.max' => 'Invalid Field Format virtualAccountName',

            // virtualAccountEmail Validation Messages
            'virtualAccountEmail.string' => 'Invalid Field Format virtualAccountEmail',
            'virtualAccountEmail.max' => 'Invalid Field Format virtualAccountEmail',

            // virtualAccountPhone Validation Messages
            'virtualAccountPhone.string' => 'Invalid Field Format virtualAccountPhone',
            'virtualAccountPhone.max' => 'Invalid Field Format virtualAccountPhone',

            // trxId Validation Messages
            'trxId.string' => 'Invalid Field Format trxId',
            'trxId.max' => 'Invalid Field Format trxId',

            // paymentRequestId Validation Messages
            'paymentRequestId.required' => 'Invalid Mandatory Field {paymentRequestId}',
            'paymentRequestId.string' => 'Invalid Field Format paymentRequestId',
            'paymentRequestId.max' => 'Invalid Field Format paymentRequestId',

            // channelCode Validation Messages
            'channelCode.numeric' => 'Invalid Field Format channelCode',
            'channelCode.digits' => 'Invalid Field Format channelCode',

            // hashedSourceAccountNo Validation Messages
            'hashedSourceAccountNo.string' => 'Invalid Field Format hashedSourceAccountNo',
            'hashedSourceAccountNo.regex' => 'Invalid Field Format hashedSourceAccountNo',
            'hashedSourceAccountNo.max' => 'Invalid Field Format hashedSourceAccountNo',

            // sourceBankCode Validation Messages
            'sourceBankCode.string' => 'Invalid Field Format sourceBankCode',
            'sourceBankCode.regex' => 'Invalid Field Format sourceBankCode',
            'sourceBankCode.size' => 'Invalid Field Format sourceBankCode',

            // paidAmount Validation Messages
            'paidAmount.required' => 'Invalid Mandatory Field {paidAmount}',
            'paidAmount.object' => 'Invalid Field Format paidAmount',
            'paidAmount.value.required_with' => 'Invalid Mandatory Field {paidAmount.value}',
            'paidAmount.value.string' => 'Invalid Field Format paidAmount.value',
            'paidAmount.value.regex' => 'Invalid Amount',
            'paidAmount.currency.required_with' => 'Invalid Mandatory Field {paidAmount.currency}',
            'paidAmount.currency.string' => 'Invalid Field Format paidAmount.currency',
            'paidAmount.currency.in' => 'Invalid Field Format paidAmount.currency',
            'paidAmount.currency.size' => 'Invalid Field Format paidAmount.currency',

            // cumulativePaymentAmount Validation Messages
            'cumulativePaymentAmount.object' => 'Invalid Field Format cumulativePaymentAmount',
            'cumulativePaymentAmount.value.required_with' => 'Invalid Mandatory Field {cumulativePaymentAmount.value}',
            'cumulativePaymentAmount.value.string' => 'Invalid Field Format cumulativePaymentAmount.value',
            'cumulativePaymentAmount.value.regex' => 'Invalid Field Format cumulativePaymentAmount.value',
            'cumulativePaymentAmount.currency.required_with' => 'Invalid Mandatory Field {cumulativePaymentAmount.currency}',
            'cumulativePaymentAmount.currency.string' => 'Invalid Field Format cumulativePaymentAmount.currency',
            'cumulativePaymentAmount.currency.in' => 'Invalid Field Format cumulativePaymentAmount.currency',
            'cumulativePaymentAmount.currency.size' => 'Invalid Field Format cumulativePaymentAmount.currency',

            // paidBills Validation Messages
            'paidBills.string' => 'Invalid Field Format paidBills',
            'paidBills.max' => 'Invalid Field Format paidBills',

            // totalAmount Validation Messages
            'totalAmount.object' => 'Invalid Field Format totalAmount',
            'totalAmount.value.required_with' => 'Invalid Mandatory Field {totalAmount.value}',
            'totalAmount.value.string' => 'Invalid Field Format totalAmount.value',
            'totalAmount.value.regex' => 'Invalid Amount',
            'totalAmount.currency.required_with' => 'Invalid Mandatory Field {totalAmount.currency}',
            'totalAmount.currency.string' => 'Invalid Field Format totalAmount.currency',
            'totalAmount.currency.in' => 'Invalid Field Format totalAmount.currency',
            'totalAmount.currency.size' => 'Invalid Field Format totalAmount.currency',

            // trxDateTime Validation Messages
            'trxDateTime.date_Format' => 'Invalid Field Format trxDateTime',
            'trxDateTime.size' => 'Invalid Field Format trxDateTime',

            // referenceNo Validation Messages
            'referenceNo.string' => 'Invalid Field Format referenceNo',
            'referenceNo.max' => 'Invalid Field Format referenceNo',

            // journalNum Validation Messages
            'journalNum.string' => 'Invalid Field Format journalNum',
            'journalNum.max' => 'Invalid Field Format journalNum',

            // paymentType Validation Messages
            'paymentType.string' => 'Invalid Field Format paymentType',
            'paymentType.max' => 'Invalid Field Format paymentType',

            // flagAdvise Validation Messages
            'flagAdvise.string' => 'Invalid Field Format flagAdvise',
            'flagAdvise.max' => 'Invalid Field Format flagAdvise',

            // subCompany Validation Messages
            'subCompany.string' => 'Invalid Field Format subCompany',
            'subCompany.max' => 'Invalid Field Format subCompany',

            // billDetails Validation Messages
            'billDetails.array' => 'Invalid Field Format billDetails',
            'billDetails.max' => 'Invalid Field Format billDetails',
            'billDetails.*.billCode.string' => 'Invalid Field Format billDetails.billCode',
            'billDetails.*.billCode.max' => 'Invalid Field Format billDetails.billCode',
            'billDetails.*.billNo.string' => 'Invalid Field Format billDetails.billNo',
            'billDetails.*.billNo.max' => 'Invalid Field Format billDetails.billNo',
            'billDetails.*.billName.string' => 'Invalid Field Format billDetails.billName',
            'billDetails.*.billName.max' => 'Invalid Field Format billDetails.billName',
            'billDetails.*.billShortName.string' => 'Invalid Field Format billDetails.billShortName',
            'billDetails.*.billShortName.max' => 'Invalid Field Format billDetails.billShortName',
            'billDetails.*.billDescription.array' => 'Invalid Field Format billDetails.billDescription',
            'billDetails.*.billDescription.english.string' => 'Invalid Field Format billDetails.billDescription.english',
            'billDetails.*.billDescription.english.max' => 'Invalid Field Format billDetails.billDescription.english',
            'billDetails.*.billDescription.indonesia.string' => 'Invalid Field Format billDetails.billDescription.indonesia',
            'billDetails.*.billDescription.indonesia.max' => 'Invalid Field Format billDetails.billDescription.indonesia',
            'billDetails.*.billSubCompany.string' => 'Invalid Field Format billDetails.billSubCompany',
            'billDetails.*.billSubCompany.max' => 'Invalid Field Format billDetails.billSubCompany',
            'billDetails.*.billAmount.array' => 'Invalid Field Format billDetails.billAmount',
            'billDetails.*.billAmount.value.required_with' => 'Invalid Mandatory Field {billDetails.billAmount.value}',
            'billDetails.*.billAmount.value.string' => 'Invalid Field Format billDetails.billAmount.value',
            'billDetails.*.billAmount.value.regex' => 'Invalid Field Format billDetails.billAmount.value',
            'billDetails.*.billAmount.currency.required_with' => 'Invalid Mandatory Field {billDetails.billAmount.currency}',
            'billDetails.*.billAmount.currency.string' => 'Invalid Field Format billDetails.billAmount.currency',
            'billDetails.*.billAmount.currency.in' => 'Invalid Field Format billDetails.billAmount.currency',
            'billDetails.*.billAmount.currency.size' => 'Invalid Field Format billDetails.billAmount.currency',
            'billDetails.*.additionalInfo.array' => 'Invalid Field Format billDetails.additionalInfo',
            'billDetails.*.billReferenceNo.numeric' => 'Invalid Field Format billDetails.billReferenceNo',

            // freeTexts Validation Messages
            'freeTexts.array' => 'Invalid Field Format freeTexts',
            'freeTexts.*.english.string' => 'Invalid Field Format freeTexts.english',
            'freeTexts.*.english.max' => 'Invalid Field Format freeTexts.english',
            'freeTexts.*.indonesia.string' => 'Invalid Field Format freeTexts.indonesia',
            'freeTexts.*.indonesia.max' => 'Invalid Field Format freeTexts.indonesia',

            // additionalInfo Validation Messages
            'additionalInfo.array' => 'Invalid Field Format additionalInfo',
            'additionalInfo.*.label.english.nullable' => 'Invalid Field Format additionalInfo.label.english',
            'additionalInfo.*.label.english.string' => 'Invalid Field Format additionalInfo.label.english',
            'additionalInfo.*.label.english.max' => 'Invalid Field Format additionalInfo.label.english',
            'additionalInfo.*.label.indonesia.nullable' => 'Invalid Field Format additionalInfo.label.indonesia',
            'additionalInfo.*.label.indonesia.string' => 'Invalid Field Format additionalInfo.label.indonesia',
            'additionalInfo.*.label.indonesia.max' => 'Invalid Field Format additionalInfo.label.indonesia',
            'additionalInfo.*.value.english.nullable' => 'Invalid Field Format additionalInfo.value.english',
            'additionalInfo.*.value.english.string' => 'Invalid Field Format additionalInfo.value.english',
            'additionalInfo.*.value.english.max' => 'Invalid Field Format additionalInfo.value.english',
            'additionalInfo.*.value.indonesia.nullable' => 'Invalid Field Format additionalInfo.value.indonesia',
            'additionalInfo.*.value.indonesia.string' => 'Invalid Field Format additionalInfo.value.indonesia',
            'additionalInfo.*.value.indonesia.max' => 'Invalid Field Format additionalInfo.value.indonesia',
        ];
    }

    /**
     * Add additional validation rules for headers.
     */
    public function withValidator(Validator $validator): void
    {
        $validator->after(function (Validator $validator) {
            $requiredHeaders = [
                'authorization',
                'content-type',
                'channel-id',
                'x-external-id',
                'x-partner-id',
                'x-signature',
                'x-timestamp',
            ];

            foreach ($requiredHeaders as $header) {
                if (! $this->header($header)) {
                    $validator->errors()->add($header, 'Invalid Mandatory Field {'.strtoupper(str_replace('_', '-', $header)).'}');

                    return;
                }
            }

            /** @var string $timestamp */
            $timestamp = $this->header('x-timestamp');

            /** @var string $partnerServiceId */
            $partnerServiceId = $this->input('partnerServiceId');

            /** @var string $customerNo */
            $customerNo = $this->input('customerNo');

            /** @var string $virtualAccountNo */
            $virtualAccountNo = $this->input('virtualAccountNo');

            /** @var ?array{value: string, currency: string} $paidAmount */
            $paidAmount = $this->input('paidAmount');

            /** @var ?array{value: string, currency: string} $totalAmount */
            $totalAmount = $this->input('totalAmount');

            /** @var string $channelId */
            $channelId = $this->header('channel-id');

            /** @var string $partnerId */
            $partnerId = $this->header('x-partner-id');

            if (empty($this->bearerToken())) {
                $validator->errors()->add('authorization', 'Invalid Field Format Authorization'); // @codeCoverageIgnore
            }

            if (! ctype_digit($channelId) || ! OauthClientMetadata::where('channel_id', $channelId)->exists()) {
                $validator->errors()->add('channel-id', 'Unauthorized. [Unknown client]');
            }

            if (! ctype_digit($partnerId) || ! OauthClientMetadata::where('partner_id', $partnerId)->exists()) {
                $validator->errors()->add('x-partner-id', 'Unauthorized. [Unknown client]');
            }

            if (! is_string($this->header('x-external-id')) || ! ctype_digit($this->header('x-external-id'))) {
                $validator->errors()->add('x-external-id', 'Invalid Field Format X-EXTERNAL-ID'); // @codeCoverageIgnore
            }

            if (! is_string($this->header('x-signature'))) {
                $validator->errors()->add('x-signature', 'Invalid Field Format X-SIGNATURE'); // @codeCoverageIgnore
            }

            if (! \DateTime::createFromFormat(DATE_ATOM, $timestamp)) {
                $validator->errors()->add('x-timestamp', 'Invalid Field Format X-TIMESTAMP');
            }

            if (strlen(trim($partnerServiceId)) > 8 || ! ctype_digit($partnerServiceId)) {
                $validator->errors()->add('partnerServiceId', 'Invalid Field Format partnerServiceId'); // @codeCoverageIgnore
            }

            if (! ctype_digit($customerNo)) {
                $validator->errors()->add('customerNo', 'Invalid Field Format customerNo'); // @codeCoverageIgnore
            }

            if ($virtualAccountNo !== ($partnerServiceId.$customerNo)) {
                $validator->errors()->add('virtualAccountNo', 'Invalid Field Format virtualAccountNo'); // @codeCoverageIgnore
            }

            if (! is_null($paidAmount) && ! is_null($totalAmount)) {
                if (! is_numeric($paidAmount['value']) || ! is_numeric($totalAmount['value'])) {
                    $validator->errors()->add('amount', 'Invalid Amount');

                    return;
                }

                if ($paidAmount['value'] !== $totalAmount['value'] || $paidAmount['currency'] !== $totalAmount['currency']) {
                    $validator->errors()->add('amount', 'Invalid Amount');

                    return;
                }
                // @codeCoverageIgnoreStart
            } else {
                $validator->errors()->add('amount', 'Invalid Amount');

                return;
            }
            // @codeCoverageIgnoreEnd
        });
    }

    /**
     * Handle a failed validation attempt.
     */
    public function failedValidation(Validator $validator): void
    {
        $errors = $validator->errors()->toArray();

        /** @var string|null $firstErrorKey */
        $firstErrorKey = array_key_first($errors);

        /** @var string $firstErrorMessage */
        $firstErrorMessage = (is_string($firstErrorKey) && isset($errors[$firstErrorKey]) && is_array($errors[$firstErrorKey]) && isset($errors[$firstErrorKey][0]))
            ? $errors[$firstErrorKey][0]
            : 'Invalid Field Format'; // @codeCoverageIgnore

        $responseCode = match (true) {
            str_contains($firstErrorMessage, 'Unauthorized') => '4012500',
            str_contains($firstErrorMessage, 'Invalid Mandatory Field') => '4002502',
            ($firstErrorMessage === 'Invalid Amount') => '4042513',
            default => '4002501',
        };

        $errorReason = match ($responseCode) {
            '4002502' => [
                'english' => "Invalid Mandatory Field {{$firstErrorKey}}",
                'indonesia' => "Format Bidang Harus Diisi {{$firstErrorKey}}",
            ],
            '4042513' => [
                'english' => 'Invalid Amount',
                'indonesia' => 'Jumlah Tidak Valid',
            ],
            default => [
                'english' => 'Invalid Field Format',
                'indonesia' => 'Format Bidang Tidak Valid',
            ],
        };

        $response = [
            'responseCode' => $responseCode,
            'responseMessage' => $firstErrorMessage,
        ];

        $errorResponse = (new DataTypeCaster)->recursiveArrayToObject(
            array_merge($response, [
                'virtualAccountData' => [
                    'paymentFlagReason' => $errorReason,
                    'partnerServiceId' => $this->input('partnerServiceId'),
                    'customerNo' => $this->input('customerNo'),
                    'virtualAccountNo' => $this->input('virtualAccountNo'),
                    'virtualAccountName' => $this->input('virtualAccountName'),
                    'virtualAccountEmail' => null,
                    'virtualAccountPhone' => null,
                    'trxId' => null,
                    'paymentRequestId' => $this->input('paymentRequestId'),
                    'paidAmount' => $this->input('paidAmount'),
                    'paidBills' => $this->input('paidBills'),
                    'totalAmount' => $this->input('totalAmount'),
                    'trxDateTime' => $this->input('trxDateTime'),
                    'referenceNo' => $this->input('referenceNo'),
                    'journalNum' => $this->input('journalNum'),
                    'paymentType' => $this->input('paymentType'),
                    'flagAdvise' => null,
                    'paymentFlagStatus' => '01',
                    'billDetails' => [],
                    'freeTexts' => [$errorReason],
                ],
                'additionalInfo' => (object) [],
            ])
        );

        $errorResponse = new TVAPaymentResource($errorResponse);

        throw new HttpResponseException(
            response()->json(
                $responseCode === '4012500' ? $response : $errorResponse,
                (int) substr((string) $responseCode, 0, 3)
            )
        );
    }
}
